session:
  token_expiry_sec: 31536000
runtime:
  http_key: defaultkey
logger:
  level: debug
console:
  username: "admin"
  password: "password"
apple:
  shared_password:
google:
  client_email:
  private_key:
